
// extracted from help.h of redis: https://github.com/antirez/redis/blob/ad78b50f62c88b6396c5ee86cda89fc2313f77af/src/help.h

export const redisCommands = [{
  name: 'APPEND',
  params: 'key value',
  description: 'Append a value to a key',
  group: 1,
  since: '2.0.0',
},
{
  name: 'AUTH',
  params: 'password',
  description: 'Authenticate to the server',
  group: 8,
  since: '1.0.0',
},
{
  name: 'BGREWRITEAOF',
  params: '-',
  description: 'Asynchronously rewrite the append-only file',
  group: 9,
  since: '1.0.0',
},
{
  name: 'BGSAVE',
  params: '-',
  description: 'Asynchronously save the dataset to disk',
  group: 9,
  since: '1.0.0',
},
{
  name: 'BITCOUNT',
  params: 'key [start end]',
  description: 'Count set bits in a string',
  group: 1,
  since: '2.6.0',
},
{
  name: 'BITFIELD',
  params: 'key [GET type offset] [SET type offset value] [INCRBY type offset increment] [OVERFLOW WRAP|SAT|FAIL]',
  description: 'Perform arbitrary bitfield integer operations on strings',
  group: 1,
  since: '3.2.0',
},
{
  name: 'BITOP',
  params: 'operation destkey key [key ...]',
  description: 'Perform bitwise operations between strings',
  group: 1,
  since: '2.6.0',
},
{
  name: 'BITPOS',
  params: 'key bit [start] [end]',
  description: 'Find first bit set or clear in a string',
  group: 1,
  since: '2.8.7',
},
{
  name: 'BLPOP',
  params: 'key [key ...] timeout',
  description: 'Remove and get the first element in a list, or block until one is available',
  group: 2,
  since: '2.0.0',
},
{
  name: 'BRPOP',
  params: 'key [key ...] timeout',
  description: 'Remove and get the last element in a list, or block until one is available',
  group: 2,
  since: '2.0.0',
},
{
  name: 'BRPOPLPUSH',
  params: 'source destination timeout',
  description: 'Pop a value from a list, push it to another list and return it; or block until one is available',
  group: 2,
  since: '2.2.0',
},
{
  name: 'BZPOPMAX',
  params: 'key [key ...] timeout',
  description: 'Remove and return the member with the highest score from one or more sorted sets, or block until one is available',
  group: 4,
  since: '5.0.0',
},
{
  name: 'BZPOPMIN',
  params: 'key [key ...] timeout',
  description: 'Remove and return the member with the lowest score from one or more sorted sets, or block until one is available',
  group: 4,
  since: '5.0.0',
},
{
  name: 'CLIENT GETNAME',
  params: '-',
  description: 'Get the current connection name',
  group: 9,
  since: '2.6.9',
},
{
  name: 'CLIENT ID',
  params: '-',
  description: 'Returns the client ID for the current connection',
  group: 9,
  since: '5.0.0',
},
{
  name: 'CLIENT KILL',
  params: '[ip:port] [ID client-id] [TYPE normal|master|slave|pubsub] [ADDR ip:port] [SKIPME yes/no]',
  description: 'Kill the connection of a client',
  group: 9,
  since: '2.4.0',
},
{
  name: 'CLIENT LIST',
  params: '-',
  description: 'Get the list of client connections',
  group: 9,
  since: '2.4.0',
},
{
  name: 'CLIENT PAUSE',
  params: 'timeout',
  description: 'Stop processing commands from clients for some time',
  group: 9,
  since: '2.9.50',
},
{
  name: 'CLIENT REPLY',
  params: 'ON|OFF|SKIP',
  description: 'Instruct the server whether to reply to commands',
  group: 9,
  since: '3.2',
},
{
  name: 'CLIENT SETNAME',
  params: 'connection-name',
  description: 'Set the current connection name',
  group: 9,
  since: '2.6.9',
},
{
  name: 'CLIENT UNBLOCK',
  params: 'client-id [TIMEOUT|ERROR]',
  description: 'Unblock a client blocked in a blocking command from a different connection',
  group: 9,
  since: '5.0.0',
},
{
  name: 'CLUSTER ADDSLOTS',
  params: 'slot [slot ...]',
  description: 'Assign new hash slots to receiving node',
  group: 12,
  since: '3.0.0',
},
{
  name: 'CLUSTER COUNT-FAILURE-REPORTS',
  params: 'node-id',
  description: 'Return the number of failure reports active for a given node',
  group: 12,
  since: '3.0.0',
},
{
  name: 'CLUSTER COUNTKEYSINSLOT',
  params: 'slot',
  description: 'Return the number of local keys in the specified hash slot',
  group: 12,
  since: '3.0.0',
},
{
  name: 'CLUSTER DELSLOTS',
  params: 'slot [slot ...]',
  description: 'Set hash slots as unbound in receiving node',
  group: 12,
  since: '3.0.0',
},
{
  name: 'CLUSTER FAILOVER',
  params: '[FORCE|TAKEOVER]',
  description: 'Forces a replica to perform a manual failover of its master.',
  group: 12,
  since: '3.0.0',
},
{
  name: 'CLUSTER FORGET',
  params: 'node-id',
  description: 'Remove a node from the nodes table',
  group: 12,
  since: '3.0.0',
},
{
  name: 'CLUSTER GETKEYSINSLOT',
  params: 'slot count',
  description: 'Return local key names in the specified hash slot',
  group: 12,
  since: '3.0.0',
},
{
  name: 'CLUSTER INFO',
  params: '-',
  description: 'Provides info about Redis Cluster node state',
  group: 12,
  since: '3.0.0',
},
{
  name: 'CLUSTER KEYSLOT',
  params: 'key',
  description: 'Returns the hash slot of the specified key',
  group: 12,
  since: '3.0.0',
},
{
  name: 'CLUSTER MEET',
  params: 'ip port',
  description: 'Force a node cluster to handshake with another node',
  group: 12,
  since: '3.0.0',
},
{
  name: 'CLUSTER NODES',
  params: '-',
  description: 'Get Cluster config for the node',
  group: 12,
  since: '3.0.0',
},
{
  name: 'CLUSTER REPLICAS',
  params: 'node-id',
  description: 'List replica nodes of the specified master node',
  group: 12,
  since: '5.0.0',
},
{
  name: 'CLUSTER REPLICATE',
  params: 'node-id',
  description: 'Reconfigure a node as a replica of the specified master node',
  group: 12,
  since: '3.0.0',
},
{
  name: 'CLUSTER RESET',
  params: '[HARD|SOFT]',
  description: 'Reset a Redis Cluster node',
  group: 12,
  since: '3.0.0',
},
{
  name: 'CLUSTER SAVECONFIG',
  params: '-',
  description: 'Forces the node to save cluster state on disk',
  group: 12,
  since: '3.0.0',
},
{
  name: 'CLUSTER SET-CONFIG-EPOCH',
  params: 'config-epoch',
  description: 'Set the configuration epoch in a new node',
  group: 12,
  since: '3.0.0',
},
{
  name: 'CLUSTER SETSLOT',
  params: 'slot IMPORTING|MIGRATING|STABLE|NODE [node-id]',
  description: 'Bind a hash slot to a specific node',
  group: 12,
  since: '3.0.0',
},
{
  name: 'CLUSTER SLAVES',
  params: 'node-id',
  description: 'List replica nodes of the specified master node',
  group: 12,
  since: '3.0.0',
},
{
  name: 'CLUSTER SLOTS',
  params: '-',
  description: 'Get array of Cluster slot to node mappings',
  group: 12,
  since: '3.0.0',
},
{
  name: 'COMMAND',
  params: '-',
  description: 'Get array of Redis command details',
  group: 9,
  since: '2.8.13',
},
{
  name: 'COMMAND COUNT',
  params: '-',
  description: 'Get total number of Redis commands',
  group: 9,
  since: '2.8.13',
},
{
  name: 'COMMAND GETKEYS',
  params: '-',
  description: 'Extract keys given a full Redis command',
  group: 9,
  since: '2.8.13',
},
{
  name: 'COMMAND INFO',
  params: 'command-name [command-name ...]',
  description: 'Get array of specific Redis command details',
  group: 9,
  since: '2.8.13',
},
{
  name: 'CONFIG GET',
  params: 'parameter',
  description: 'Get the value of a configuration parameter',
  group: 9,
  since: '2.0.0',
},
{
  name: 'CONFIG RESETSTAT',
  params: '-',
  description: 'Reset the stats returned by INFO',
  group: 9,
  since: '2.0.0',
},
{
  name: 'CONFIG REWRITE',
  params: '-',
  description: 'Rewrite the configuration file with the in memory configuration',
  group: 9,
  since: '2.8.0',
},
{
  name: 'CONFIG SET',
  params: 'parameter value',
  description: 'Set a configuration parameter to the given value',
  group: 9,
  since: '2.0.0',
},
{
  name: 'DBSIZE',
  params: '-',
  description: 'Return the number of keys in the selected database',
  group: 9,
  since: '1.0.0',
},
{
  name: 'DEBUG OBJECT',
  params: 'key',
  description: 'Get debugging information about a key',
  group: 9,
  since: '1.0.0',
},
{
  name: 'DEBUG SEGFAULT',
  params: '-',
  description: 'Make the server crash',
  group: 9,
  since: '1.0.0',
},
{
  name: 'DECR',
  params: 'key',
  description: 'Decrement the integer value of a key by one',
  group: 1,
  since: '1.0.0',
},
{
  name: 'DECRBY',
  params: 'key decrement',
  description: 'Decrement the integer value of a key by the given number',
  group: 1,
  since: '1.0.0',
},
{
  name: 'DEL',
  params: 'key [key ...]',
  description: 'Delete a key',
  group: 0,
  since: '1.0.0',
},
{
  name: 'DISCARD',
  params: '-',
  description: 'Discard all commands issued after MULTI',
  group: 7,
  since: '2.0.0',
},
{
  name: 'DUMP',
  params: 'key',
  description: 'Return a serialized version of the value stored at the specified key.',
  group: 0,
  since: '2.6.0',
},
{
  name: 'ECHO',
  params: 'message',
  description: 'Echo the given string',
  group: 8,
  since: '1.0.0',
},
{
  name: 'EVAL',
  params: 'script numkeys key [key ...] arg [arg ...]',
  description: 'Execute a Lua script server side',
  group: 10,
  since: '2.6.0',
},
{
  name: 'EVALSHA',
  params: 'sha1 numkeys key [key ...] arg [arg ...]',
  description: 'Execute a Lua script server side',
  group: 10,
  since: '2.6.0',
},
{
  name: 'EXEC',
  params: '-',
  description: 'Execute all commands issued after MULTI',
  group: 7,
  since: '1.2.0',
},
{
  name: 'EXISTS',
  params: 'key [key ...]',
  description: 'Determine if a key exists',
  group: 0,
  since: '1.0.0',
},
{
  name: 'EXPIRE',
  params: 'key seconds',
  description: "Set a key's time to live in seconds",
  group: 0,
  since: '1.0.0',
},
{
  name: 'EXPIREAT',
  params: 'key timestamp',
  description: 'Set the expiration for a key as a UNIX timestamp',
  group: 0,
  since: '1.2.0',
},
{
  name: 'FLUSHALL',
  params: '[ASYNC]',
  description: 'Remove all keys from all databases',
  group: 9,
  since: '1.0.0',
},
{
  name: 'FLUSHDB',
  params: '[ASYNC]',
  description: 'Remove all keys from the current database',
  group: 9,
  since: '1.0.0',
},
{
  name: 'GEOADD',
  params: 'key longitude latitude member [longitude latitude member ...]',
  description: 'Add one or more geospatial items in the geospatial index represented using a sorted set',
  group: 13,
  since: '3.2.0',
},
{
  name: 'GEODIST',
  params: 'key member1 member2 [unit]',
  description: 'Returns the distance between two members of a geospatial index',
  group: 13,
  since: '3.2.0',
},
{
  name: 'GEOHASH',
  params: 'key member [member ...]',
  description: 'Returns members of a geospatial index as standard geohash strings',
  group: 13,
  since: '3.2.0',
},
{
  name: 'GEOPOS',
  params: 'key member [member ...]',
  description: 'Returns longitude and latitude of members of a geospatial index',
  group: 13,
  since: '3.2.0',
},
{
  name: 'GEORADIUS',
  params: 'key longitude latitude radius m|km|ft|mi [WITHCOORD] [WITHDIST] [WITHHASH] [COUNT count] [ASC|DESC] [STORE key] [STOREDIST key]',
  description: 'Query a sorted set representing a geospatial index to fetch members matching a given maximum distance from a point',
  group: 13,
  since: '3.2.0',
},
{
  name: 'GEORADIUSBYMEMBER',
  params: 'key member radius m|km|ft|mi [WITHCOORD] [WITHDIST] [WITHHASH] [COUNT count] [ASC|DESC] [STORE key] [STOREDIST key]',
  description: 'Query a sorted set representing a geospatial index to fetch members matching a given maximum distance from a member',
  group: 13,
  since: '3.2.0',
},
{
  name: 'GET',
  params: 'key',
  description: 'Get the value of a key',
  group: 1,
  since: '1.0.0',
},
{
  name: 'GETBIT',
  params: 'key offset',
  description: 'Returns the bit value at offset in the string value stored at key',
  group: 1,
  since: '2.2.0',
},
{
  name: 'GETRANGE',
  params: 'key start end',
  description: 'Get a substring of the string stored at a key',
  group: 1,
  since: '2.4.0',
},
{
  name: 'GETSET',
  params: 'key value',
  description: 'Set the string value of a key and return its old value',
  group: 1,
  since: '1.0.0',
},
{
  name: 'HDEL',
  params: 'key field [field ...]',
  description: 'Delete one or more hash fields',
  group: 5,
  since: '2.0.0',
},
{
  name: 'HEXISTS',
  params: 'key field',
  description: 'Determine if a hash field exists',
  group: 5,
  since: '2.0.0',
},
{
  name: 'HGET',
  params: 'key field',
  description: 'Get the value of a hash field',
  group: 5,
  since: '2.0.0',
},
{
  name: 'HGETALL',
  params: 'key',
  description: 'Get all the fields and values in a hash',
  group: 5,
  since: '2.0.0',
},
{
  name: 'HINCRBY',
  params: 'key field increment',
  description: 'Increment the integer value of a hash field by the given number',
  group: 5,
  since: '2.0.0',
},
{
  name: 'HINCRBYFLOAT',
  params: 'key field increment',
  description: 'Increment the float value of a hash field by the given amount',
  group: 5,
  since: '2.6.0',
},
{
  name: 'HKEYS',
  params: 'key',
  description: 'Get all the fields in a hash',
  group: 5,
  since: '2.0.0',
},
{
  name: 'HLEN',
  params: 'key',
  description: 'Get the number of fields in a hash',
  group: 5,
  since: '2.0.0',
},
{
  name: 'HMGET',
  params: 'key field [field ...]',
  description: 'Get the values of all the given hash fields',
  group: 5,
  since: '2.0.0',
},
{
  name: 'HMSET',
  params: 'key field value [field value ...]',
  description: 'Set multiple hash fields to multiple values',
  group: 5,
  since: '2.0.0',
},
{
  name: 'HSCAN',
  params: 'key cursor [MATCH pattern] [COUNT count]',
  description: 'Incrementally iterate hash fields and associated values',
  group: 5,
  since: '2.8.0',
},
{
  name: 'HSET',
  params: 'key field value',
  description: 'Set the string value of a hash field',
  group: 5,
  since: '2.0.0',
},
{
  name: 'HSETNX',
  params: 'key field value',
  description: 'Set the value of a hash field, only if the field does not exist',
  group: 5,
  since: '2.0.0',
},
{
  name: 'HSTRLEN',
  params: 'key field',
  description: 'Get the length of the value of a hash field',
  group: 5,
  since: '3.2.0',
},
{
  name: 'HVALS',
  params: 'key',
  description: 'Get all the values in a hash',
  group: 5,
  since: '2.0.0',
},
{
  name: 'INCR',
  params: 'key',
  description: 'Increment the integer value of a key by one',
  group: 1,
  since: '1.0.0',
},
{
  name: 'INCRBY',
  params: 'key increment',
  description: 'Increment the integer value of a key by the given amount',
  group: 1,
  since: '1.0.0',
},
{
  name: 'INCRBYFLOAT',
  params: 'key increment',
  description: 'Increment the float value of a key by the given amount',
  group: 1,
  since: '2.6.0',
},
{
  name: 'INFO',
  params: '[section]',
  description: 'Get information and statistics about the server',
  group: 9,
  since: '1.0.0',
},
{
  name: 'KEYS',
  params: 'pattern',
  description: 'Find all keys matching the given pattern',
  group: 0,
  since: '1.0.0',
},
{
  name: 'LASTSAVE',
  params: '-',
  description: 'Get the UNIX time stamp of the last successful save to disk',
  group: 9,
  since: '1.0.0',
},
{
  name: 'LINDEX',
  params: 'key index',
  description: 'Get an element from a list by its index',
  group: 2,
  since: '1.0.0',
},
{
  name: 'LINSERT',
  params: 'key BEFORE|AFTER pivot value',
  description: 'Insert an element before or after another element in a list',
  group: 2,
  since: '2.2.0',
},
{
  name: 'LLEN',
  params: 'key',
  description: 'Get the length of a list',
  group: 2,
  since: '1.0.0',
},
{
  name: 'LPOP',
  params: 'key',
  description: 'Remove and get the first element in a list',
  group: 2,
  since: '1.0.0',
},
{
  name: 'LPUSH',
  params: 'key value [value ...]',
  description: 'Prepend one or multiple values to a list',
  group: 2,
  since: '1.0.0',
},
{
  name: 'LPUSHX',
  params: 'key value',
  description: 'Prepend a value to a list, only if the list exists',
  group: 2,
  since: '2.2.0',
},
{
  name: 'LRANGE',
  params: 'key start stop',
  description: 'Get a range of elements from a list',
  group: 2,
  since: '1.0.0',
},
{
  name: 'LREM',
  params: 'key count value',
  description: 'Remove elements from a list',
  group: 2,
  since: '1.0.0',
},
{
  name: 'LSET',
  params: 'key index value',
  description: 'Set the value of an element in a list by its index',
  group: 2,
  since: '1.0.0',
},
{
  name: 'LTRIM',
  params: 'key start stop',
  description: 'Trim a list to the specified range',
  group: 2,
  since: '1.0.0',
},
{
  name: 'MEMORY DOCTOR',
  params: '-',
  description: 'Outputs memory problems report',
  group: 9,
  since: '4.0.0',
},
{
  name: 'MEMORY HELP',
  params: '-',
  description: 'Show helpful text about the different subcommands',
  group: 9,
  since: '4.0.0',
},
{
  name: 'MEMORY MALLOC-STATS',
  params: '-',
  description: 'Show allocator internal stats',
  group: 9,
  since: '4.0.0',
},
{
  name: 'MEMORY PURGE',
  params: '-',
  description: 'Ask the allocator to release memory',
  group: 9,
  since: '4.0.0',
},
{
  name: 'MEMORY STATS',
  params: '-',
  description: 'Show memory usage details',
  group: 9,
  since: '4.0.0',
},
{
  name: 'MEMORY USAGE',
  params: 'key [SAMPLES count]',
  description: 'Estimate the memory usage of a key',
  group: 9,
  since: '4.0.0',
},
{
  name: 'MGET',
  params: 'key [key ...]',
  description: 'Get the values of all the given keys',
  group: 1,
  since: '1.0.0',
},
{
  name: 'MIGRATE',
  params: 'host port key|"" destination-db timeout [COPY] [REPLACE] [KEYS key]',
  description: 'Atomically transfer a key from a Redis instance to another one.',
  group: 0,
  since: '2.6.0',
},
{
  name: 'MONITOR',
  params: '-',
  description: 'Listen for all requests received by the server in real time',
  group: 9,
  since: '1.0.0',
},
{
  name: 'MOVE',
  params: 'key db',
  description: 'Move a key to another database',
  group: 0,
  since: '1.0.0',
},
{
  name: 'MSET',
  params: 'key value [key value ...]',
  description: 'Set multiple keys to multiple values',
  group: 1,
  since: '1.0.1',
},
{
  name: 'MSETNX',
  params: 'key value [key value ...]',
  description: 'Set multiple keys to multiple values, only if none of the keys exist',
  group: 1,
  since: '1.0.1',
},
{
  name: 'MULTI',
  params: '-',
  description: 'Mark the start of a transaction block',
  group: 7,
  since: '1.2.0',
},
{
  name: 'OBJECT',
  params: 'subcommand [arguments [arguments ...]]',
  description: 'Inspect the internals of Redis objects',
  group: 0,
  since: '2.2.3',
},
{
  name: 'PERSIST',
  params: 'key',
  description: 'Remove the expiration from a key',
  group: 0,
  since: '2.2.0',
},
{
  name: 'PEXPIRE',
  params: 'key milliseconds',
  description: "Set a key's time to live in milliseconds",
  group: 0,
  since: '2.6.0',
},
{
  name: 'PEXPIREAT',
  params: 'key milliseconds-timestamp',
  description: 'Set the expiration for a key as a UNIX timestamp specified in milliseconds',
  group: 0,
  since: '2.6.0',
},
{
  name: 'PFADD',
  params: 'key element [element ...]',
  description: 'Adds the specified elements to the specified HyperLogLog.',
  group: 11,
  since: '2.8.9',
},
{
  name: 'PFCOUNT',
  params: 'key [key ...]',
  description: 'Return the approximated cardinality of the set(s) observed by the HyperLogLog at key(s).',
  group: 11,
  since: '2.8.9',
},
{
  name: 'PFMERGE',
  params: 'destkey sourcekey [sourcekey ...]',
  description: 'Merge N different HyperLogLogs into a single one.',
  group: 11,
  since: '2.8.9',
},
{
  name: 'PING',
  params: '[message]',
  description: 'Ping the server',
  group: 8,
  since: '1.0.0',
},
{
  name: 'PSETEX',
  params: 'key milliseconds value',
  description: 'Set the value and expiration in milliseconds of a key',
  group: 1,
  since: '2.6.0',
},
{
  name: 'PSUBSCRIBE',
  params: 'pattern [pattern ...]',
  description: 'Listen for messages published to channels matching the given patterns',
  group: 6,
  since: '2.0.0',
},
{
  name: 'PTTL',
  params: 'key',
  description: 'Get the time to live for a key in milliseconds',
  group: 0,
  since: '2.6.0',
},
{
  name: 'PUBLISH',
  params: 'channel message',
  description: 'Post a message to a channel',
  group: 6,
  since: '2.0.0',
},
{
  name: 'PUBSUB',
  params: 'subcommand [argument [argument ...]]',
  description: 'Inspect the state of the Pub/Sub subsystem',
  group: 6,
  since: '2.8.0',
},
{
  name: 'PUNSUBSCRIBE',
  params: '[pattern [pattern ...]]',
  description: 'Stop listening for messages posted to channels matching the given patterns',
  group: 6,
  since: '2.0.0',
},
{
  name: 'QUIT',
  params: '-',
  description: 'Close the connection',
  group: 8,
  since: '1.0.0',
},
{
  name: 'RANDOMKEY',
  params: '-',
  description: 'Return a random key from the keyspace',
  group: 0,
  since: '1.0.0',
},
{
  name: 'READONLY',
  params: '-',
  description: 'Enables read queries for a connection to a cluster replica node',
  group: 12,
  since: '3.0.0',
},
{
  name: 'READWRITE',
  params: '-',
  description: 'Disables read queries for a connection to a cluster replica node',
  group: 12,
  since: '3.0.0',
},
{
  name: 'RENAME',
  params: 'key newkey',
  description: 'Rename a key',
  group: 0,
  since: '1.0.0',
},
{
  name: 'RENAMENX',
  params: 'key newkey',
  description: 'Rename a key, only if the new key does not exist',
  group: 0,
  since: '1.0.0',
},
{
  name: 'REPLICAOF',
  params: 'host port',
  description: 'Make the server a replica of another instance, or promote it as master.',
  group: 9,
  since: '5.0.0',
},
{
  name: 'RESTORE',
  params: 'key ttl serialized-value [REPLACE]',
  description: 'Create a key using the provided serialized value, previously obtained using DUMP.',
  group: 0,
  since: '2.6.0',
},
{
  name: 'ROLE',
  params: '-',
  description: 'Return the role of the instance in the context of replication',
  group: 9,
  since: '2.8.12',
},
{
  name: 'RPOP',
  params: 'key',
  description: 'Remove and get the last element in a list',
  group: 2,
  since: '1.0.0',
},
{
  name: 'RPOPLPUSH',
  params: 'source destination',
  description: 'Remove the last element in a list, prepend it to another list and return it',
  group: 2,
  since: '1.2.0',
},
{
  name: 'RPUSH',
  params: 'key value [value ...]',
  description: 'Append one or multiple values to a list',
  group: 2,
  since: '1.0.0',
},
{
  name: 'RPUSHX',
  params: 'key value',
  description: 'Append a value to a list, only if the list exists',
  group: 2,
  since: '2.2.0',
},
{
  name: 'SADD',
  params: 'key member [member ...]',
  description: 'Add one or more members to a set',
  group: 3,
  since: '1.0.0',
},
{
  name: 'SAVE',
  params: '-',
  description: 'Synchronously save the dataset to disk',
  group: 9,
  since: '1.0.0',
},
{
  name: 'SCAN',
  params: 'cursor [MATCH pattern] [COUNT count]',
  description: 'Incrementally iterate the keys space',
  group: 0,
  since: '2.8.0',
},
{
  name: 'SCARD',
  params: 'key',
  description: 'Get the number of members in a set',
  group: 3,
  since: '1.0.0',
},
{
  name: 'SCRIPT DEBUG',
  params: 'YES|SYNC|NO',
  description: 'Set the debug mode for executed scripts.',
  group: 10,
  since: '3.2.0',
},
{
  name: 'SCRIPT EXISTS',
  params: 'sha1 [sha1 ...]',
  description: 'Check existence of scripts in the script cache.',
  group: 10,
  since: '2.6.0',
},
{
  name: 'SCRIPT FLUSH',
  params: '-',
  description: 'Remove all the scripts from the script cache.',
  group: 10,
  since: '2.6.0',
},
{
  name: 'SCRIPT KILL',
  params: '-',
  description: 'Kill the script currently in execution.',
  group: 10,
  since: '2.6.0',
},
{
  name: 'SCRIPT LOAD',
  params: 'script',
  description: 'Load the specified Lua script into the script cache.',
  group: 10,
  since: '2.6.0',
},
{
  name: 'SDIFF',
  params: 'key [key ...]',
  description: 'Subtract multiple sets',
  group: 3,
  since: '1.0.0',
},
{
  name: 'SDIFFSTORE',
  params: 'destination key [key ...]',
  description: 'Subtract multiple sets and store the resulting set in a key',
  group: 3,
  since: '1.0.0',
},
{
  name: 'SELECT',
  params: 'index',
  description: 'Change the selected database for the current connection',
  group: 8,
  since: '1.0.0',
},
{
  name: 'SET',
  params: 'key value [expiration EX seconds|PX milliseconds] [NX|XX]',
  description: 'Set the string value of a key',
  group: 1,
  since: '1.0.0',
},
{
  name: 'SETBIT',
  params: 'key offset value',
  description: 'Sets or clears the bit at offset in the string value stored at key',
  group: 1,
  since: '2.2.0',
},
{
  name: 'SETEX',
  params: 'key seconds value',
  description: 'Set the value and expiration of a key',
  group: 1,
  since: '2.0.0',
},
{
  name: 'SETNX',
  params: 'key value',
  description: 'Set the value of a key, only if the key does not exist',
  group: 1,
  since: '1.0.0',
},
{
  name: 'SETRANGE',
  params: 'key offset value',
  description: 'Overwrite part of a string at key starting at the specified offset',
  group: 1,
  since: '2.2.0',
},
{
  name: 'SHUTDOWN',
  params: '[NOSAVE|SAVE]',
  description: 'Synchronously save the dataset to disk and then shut down the server',
  group: 9,
  since: '1.0.0',
},
{
  name: 'SINTER',
  params: 'key [key ...]',
  description: 'Intersect multiple sets',
  group: 3,
  since: '1.0.0',
},
{
  name: 'SINTERSTORE',
  params: 'destination key [key ...]',
  description: 'Intersect multiple sets and store the resulting set in a key',
  group: 3,
  since: '1.0.0',
},
{
  name: 'SISMEMBER',
  params: 'key member',
  description: 'Determine if a given value is a member of a set',
  group: 3,
  since: '1.0.0',
},
{
  name: 'SLAVEOF',
  params: 'host port',
  description: 'Make the server a replica of another instance, or promote it as master. Deprecated starting with Redis 5. Use REPLICAOF instead.',
  group: 9,
  since: '1.0.0',
},
{
  name: 'SLOWLOG',
  params: 'subcommand [argument]',
  description: 'Manages the Redis slow queries log',
  group: 9,
  since: '2.2.12',
},
{
  name: 'SMEMBERS',
  params: 'key',
  description: 'Get all the members in a set',
  group: 3,
  since: '1.0.0',
},
{
  name: 'SMOVE',
  params: 'source destination member',
  description: 'Move a member from one set to another',
  group: 3,
  since: '1.0.0',
},
{
  name: 'SORT',
  params: 'key [BY pattern] [LIMIT offset count] [GET pattern [GET pattern ...]] [ASC|DESC] [ALPHA] [STORE destination]',
  description: 'Sort the elements in a list, set or sorted set',
  group: 0,
  since: '1.0.0',
},
{
  name: 'SPOP',
  params: 'key [count]',
  description: 'Remove and return one or multiple random members from a set',
  group: 3,
  since: '1.0.0',
},
{
  name: 'SRANDMEMBER',
  params: 'key [count]',
  description: 'Get one or multiple random members from a set',
  group: 3,
  since: '1.0.0',
},
{
  name: 'SREM',
  params: 'key member [member ...]',
  description: 'Remove one or more members from a set',
  group: 3,
  since: '1.0.0',
},
{
  name: 'SSCAN',
  params: 'key cursor [MATCH pattern] [COUNT count]',
  description: 'Incrementally iterate Set elements',
  group: 3,
  since: '2.8.0',
},
{
  name: 'STRLEN',
  params: 'key',
  description: 'Get the length of the value stored in a key',
  group: 1,
  since: '2.2.0',
},
{
  name: 'SUBSCRIBE',
  params: 'channel [channel ...]',
  description: 'Listen for messages published to the given channels',
  group: 6,
  since: '2.0.0',
},
{
  name: 'SUNION',
  params: 'key [key ...]',
  description: 'Add multiple sets',
  group: 3,
  since: '1.0.0',
},
{
  name: 'SUNIONSTORE',
  params: 'destination key [key ...]',
  description: 'Add multiple sets and store the resulting set in a key',
  group: 3,
  since: '1.0.0',
},
{
  name: 'SWAPDB',
  params: 'index index',
  description: 'Swaps two Redis databases',
  group: 8,
  since: '4.0.0',
},
{
  name: 'SYNC',
  params: '-',
  description: 'Internal command used for replication',
  group: 9,
  since: '1.0.0',
},
{
  name: 'TIME',
  params: '-',
  description: 'Return the current server time',
  group: 9,
  since: '2.6.0',
},
{
  name: 'TOUCH',
  params: 'key [key ...]',
  description: 'Alters the last access time of a key(s). Returns the number of existing keys specified.',
  group: 0,
  since: '3.2.1',
},
{
  name: 'TTL',
  params: 'key',
  description: 'Get the time to live for a key',
  group: 0,
  since: '1.0.0',
},
{
  name: 'TYPE',
  params: 'key',
  description: 'Determine the type stored at key',
  group: 0,
  since: '1.0.0',
},
{
  name: 'UNLINK',
  params: 'key [key ...]',
  description: 'Delete a key asynchronously in another thread. Otherwise it is just as DEL, but non blocking.',
  group: 0,
  since: '4.0.0',
},
{
  name: 'UNSUBSCRIBE',
  params: '[channel [channel ...]]',
  description: 'Stop listening for messages posted to the given channels',
  group: 6,
  since: '2.0.0',
},
{
  name: 'UNWATCH',
  params: '-',
  description: 'Forget about all watched keys',
  group: 7,
  since: '2.2.0',
},
{
  name: 'WAIT',
  params: 'numreplicas timeout',
  description: 'Wait for the synchronous replication of all the write commands sent in the context of the current connection',
  group: 0,
  since: '3.0.0',
},
{
  name: 'WATCH',
  params: 'key [key ...]',
  description: 'Watch the given keys to determine execution of the MULTI/EXEC block',
  group: 7,
  since: '2.2.0',
},
{
  name: 'XACK',
  params: 'key group ID [ID ...]',
  description: 'Marks a pending message as correctly processed, effectively removing it from the pending entries list of the consumer group. Return value of the command is the number of messages successfully group: acknowledged, that is, the IDs we were actually able to resolve in the PEL.',
  group: 14,
  since: '5.0.0',
},
{
  name: 'XADD',
  params: 'key ID field string [field string ...]',
  description: 'Appends a new entry to a stream',
  group: 14,
  since: '5.0.0',
},
{
  name: 'XCLAIM',
  params: 'key group consumer min-idle-time ID [ID ...] [IDLE ms] [TIME ms-unix-time] [RETRYCOUNT count] [force] [justid]',
  description: 'Changes (or acquires) ownership of a message in a consumer group, as if the message was delivered to the specified consumer.',
  group: 14,
  since: '5.0.0',
},
{
  name: 'XDEL',
  params: 'key ID [ID ...]',
  description: 'Removes the specified entries from the stream. Returns the number of items actually deleted, that may be different from the number of IDs passed in case certain IDs do not exist.',
  group: 14,
  since: '5.0.0',
},
{
  name: 'XGROUP',
  params: '[CREATE key groupname id-or-$] [SETID key id-or-$] [DESTROY key groupname] [DELCONSUMER key groupname consumername]',
  description: 'Create, destroy, and manage consumer groups.',
  group: 14,
  since: '5.0.0',
},
{
  name: 'XINFO',
  params: '[CONSUMERS key groupname] [GROUPS key] [STREAM key] [HELP]',
  description: 'Get information on streams and consumer groups',
  group: 14,
  since: '5.0.0',
},
{
  name: 'XLEN',
  params: 'key',
  description: 'Return the number of entires in a stream',
  group: 14,
  since: '5.0.0',
},
{
  name: 'XPENDING',
  params: 'key group [start end count] [consumer]',
  description: 'Return information and entries from a stream consumer group pending entries list, that are messages fetched but never acknowledged.',
  group: 14,
  since: '5.0.0',
},
{
  name: 'XRANGE',
  params: 'key start end [COUNT count]',
  description: 'Return a range of elements in a stream, with IDs matching the specified IDs interval',
  group: 14,
  since: '5.0.0',
},
{
  name: 'XREAD',
  params: '[COUNT count] [BLOCK milliseconds] STREAMS key [key ...] ID [ID ...]',
  description: 'Return never seen elements in multiple streams, with IDs greater than the ones reported by the caller for each stream. Can block.',
  group: 14,
  since: '5.0.0',
},
{
  name: 'XREADGROUP',
  params: 'GROUP group consumer [COUNT count] [BLOCK milliseconds] STREAMS key [key ...] ID [ID ...]',
  description: 'Return new entries from a stream using a consumer group, or access the history of the pending entries for a given consumer. Can block.',
  group: 14,
  since: '5.0.0',
},
{
  name: 'XREVRANGE',
  params: 'key end start [COUNT count]',
  description: 'Return a range of elements in a stream, with IDs matching the specified IDs interval, in reverse order (from greater to smaller IDs) compared to XRANGE',
  group: 14,
  since: '5.0.0',
},
{
  name: 'XTRIM',
  params: 'key MAXLEN [~] count',
  description: "Trims the stream to (approximately if '~' is passed) a certain size",
  group: 14,
  since: '5.0.0',
},
{
  name: 'ZADD',
  params: 'key [NX|XX] [CH] [INCR] score member [score member ...]',
  description: 'Add one or more members to a sorted set, or update its score if it already exists',
  group: 4,
  since: '1.2.0',
},
{
  name: 'ZCARD',
  params: 'key',
  description: 'Get the number of members in a sorted set',
  group: 4,
  since: '1.2.0',
},
{
  name: 'ZCOUNT',
  params: 'key min max',
  description: 'Count the members in a sorted set with scores within the given values',
  group: 4,
  since: '2.0.0',
},
{
  name: 'ZINCRBY',
  params: 'key increment member',
  description: 'Increment the score of a member in a sorted set',
  group: 4,
  since: '1.2.0',
},
{
  name: 'ZINTERSTORE',
  params: 'destination numkeys key [key ...] [WEIGHTS weight] [AGGREGATE SUM|MIN|MAX]',
  description: 'Intersect multiple sorted sets and store the resulting sorted set in a new key',
  group: 4,
  since: '2.0.0',
},
{
  name: 'ZLEXCOUNT',
  params: 'key min max',
  description: 'Count the number of members in a sorted set between a given lexicographical range',
  group: 4,
  since: '2.8.9',
},
{
  name: 'ZPOPMAX',
  params: 'key [count]',
  description: 'Remove and return members with the highest scores in a sorted set',
  group: 4,
  since: '5.0.0',
},
{
  name: 'ZPOPMIN',
  params: 'key [count]',
  description: 'Remove and return members with the lowest scores in a sorted set',
  group: 4,
  since: '5.0.0',
},
{
  name: 'ZRANGE',
  params: 'key start stop [WITHSCORES]',
  description: 'Return a range of members in a sorted set, by index',
  group: 4,
  since: '1.2.0',
},
{
  name: 'ZRANGEBYLEX',
  params: 'key min max [LIMIT offset count]',
  description: 'Return a range of members in a sorted set, by lexicographical range',
  group: 4,
  since: '2.8.9',
},
{
  name: 'ZRANGEBYSCORE',
  params: 'key min max [WITHSCORES] [LIMIT offset count]',
  description: 'Return a range of members in a sorted set, by score',
  group: 4,
  since: '1.0.5',
},
{
  name: 'ZRANK',
  params: 'key member',
  description: 'Determine the index of a member in a sorted set',
  group: 4,
  since: '2.0.0',
},
{
  name: 'ZREM',
  params: 'key member [member ...]',
  description: 'Remove one or more members from a sorted set',
  group: 4,
  since: '1.2.0',
},
{
  name: 'ZREMRANGEBYLEX',
  params: 'key min max',
  description: 'Remove all members in a sorted set between the given lexicographical range',
  group: 4,
  since: '2.8.9',
},
{
  name: 'ZREMRANGEBYRANK',
  params: 'key start stop',
  description: 'Remove all members in a sorted set within the given indexes',
  group: 4,
  since: '2.0.0',
},
{
  name: 'ZREMRANGEBYSCORE',
  params: 'key min max',
  description: 'Remove all members in a sorted set within the given scores',
  group: 4,
  since: '1.2.0',
},
{
  name: 'ZREVRANGE',
  params: 'key start stop [WITHSCORES]',
  description: 'Return a range of members in a sorted set, by index, with scores ordered from high to low',
  group: 4,
  since: '1.2.0',
},
{
  name: 'ZREVRANGEBYLEX',
  params: 'key max min [LIMIT offset count]',
  description: 'Return a range of members in a sorted set, by lexicographical range, ordered from higher to lower strings.',
  group: 4,
  since: '2.8.9',
},
{
  name: 'ZREVRANGEBYSCORE',
  params: 'key max min [WITHSCORES] [LIMIT offset count]',
  description: 'Return a range of members in a sorted set, by score, with scores ordered from high to low',
  group: 4,
  since: '2.2.0',
},
{
  name: 'ZREVRANK',
  params: 'key member',
  description: 'Determine the index of a member in a sorted set, with scores ordered from high to low',
  group: 4,
  since: '2.0.0',
},
{
  name: 'ZSCAN',
  params: 'key cursor [MATCH pattern] [COUNT count]',
  description: 'Incrementally iterate sorted sets elements and associated scores',
  group: 4,
  since: '2.8.0',
},
{
  name: 'ZSCORE',
  params: 'key member',
  description: 'Get the score associated with the given member in a sorted set',
  group: 4,
  since: '1.2.0',
},
{
  name: 'ZUNIONSTORE',
  params: 'destination numkeys key [key ...] [WEIGHTS weight] [AGGREGATE SUM|MIN|MAX]',
  description: 'Add multiple sorted sets and store the resulting sorted set in a new key',
  group: 4,
  since: '2.0.0',
}]
